import type { SolutionConf, Word } from "wasm_crossword_gen";

const words = [
	{ text: "finders", clue: null },
	{ text: "friends", clue: null },
	{ text: "redfins", clue: null },
	{ text: "diners", clue: null },
	{ text: "fiends", clue: null },
	{ text: "finder", clue: null },
	{ text: "friend", clue: null },
	{ text: "infers", clue: null },
	{ text: "redfin", clue: null },
	{ text: "refind", clue: null },
	{ text: "rinsed", clue: null },
	{ text: "snider", clue: null },
	{ text: "diner", clue: null },
	{ text: "dries", clue: null },
	{ text: "fends", clue: null },
	{ text: "ferns", clue: null },
	{ text: "feind", clue: null },
	{ text: "finds", clue: null },
	{ text: "fined", clue: null },
	{ text: "fired", clue: null },
	{ text: "fires", clue: null },
	{ text: "fried", clue: null },
	{ text: "fries", clue: null },
	{ text: "infer", clue: null },
	{ text: "nerds", clue: null },
	{ text: "reins", clue: null },
	{ text: "rends", clue: null },
	{ text: "resin", clue: null },
	{ text: "rides", clue: null },
	{ text: "rinse", clue: null },
	{ text: "risen", clue: null },
	{ text: "serif", clue: null },
	{ text: "sired", clue: null },
	{ text: "siren", clue: null },
	{ text: "snide", clue: null },
	{ text: "dens", clue: null },
	{ text: "dies", clue: null },
	{ text: "dine", clue: null },
	{ text: "dire", clue: null },
	{ text: "ends", clue: null },
	{ text: "feds", clue: null },
	{ text: "fend", clue: null },
	{ text: "fens", clue: null },
	{ text: "fern", clue: null },
	{ text: "find", clue: null },
	{ text: "fine", clue: null },
	{ text: "fins", clue: null },
	{ text: "fire", clue: null },
	{ text: "firs", clue: null },
	{ text: "ides", clue: null },
	{ text: "ires", clue: null },
	{ text: "nerd", clue: null },
	{ text: "refs", clue: null },
	{ text: "rein", clue: null },
	{ text: "rend", clue: null },
	{ text: "ride", clue: null },
	{ text: "rids", clue: null },
	{ text: "rife", clue: null },
	{ text: "send", clue: null },
	{ text: "side", clue: null },
	{ text: "sine", clue: null },
	{ text: "sire", clue: null },
];

export const hardcoded_conf: SolutionConf = {
	height: 10,
	width: 10,
	max_words: 15,
	initial_placement: null,
	words,
	requirements: {
		max_retries: 100,
		min_words: 8,
		min_letters_per_word: 3,
		max_empty_columns: 1,
		max_empty_rows: 1
	}
};
